### PR TITLE
server.c: fix build failure as static library

### PR DESCRIPTION
**Pull request by giuliobenetti**
As static library strncpy() can't determine precise maximum characters because strlen() is variable, so to fix build failure let's convert 3 lines into one by using strdup() that does the same as the actual code.

### CODE REVIEW

**Comment by radarsat1** [comment]
can you explain the build failure you are talking about? your change is good so i merged but i don't see what it has to do with building as a static library.

**Comment by radarsat1** [comment]
ps i still push to master in sf, though yes i might eventually drop it, it's mostly just used as a web host now

**Comment by giuliobenetti** [comment]
> can you explain the build failure you are talking about? your change is good so i merged but i don't see what it has to do with building as a static library.

Pardon @radarsat1, that was a bad commit log :-/
I've digged and the reason is that when build-testing using buildroot/utils/test-pkg there is a toolchain called br-arm-full-static where flag -Werror is enabled and that in order enables -Wstringop-overflow resulting in error:
```
server.c: In function ‘dispatch_method’:
server.c:2067:21: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
 2067 |                     strncpy(tmp, it->path + len, tmplen);
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
server.c:2065:40: note: length computed here
 2065 |                     int tmplen = (int) strlen(it->path + len) + 1;
      |                                        ^~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

So this is a fix for a possible buffer overflow.
